---
Name: snapshot-extensions
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Versioned\RecursivePublishable:
    class: SilverStripe\Snapshots\SnapshotPublishable
SilverStripe\Versioned\ChangeSetItem:
  extensions:
    - SilverStripe\Snapshots\SnapshotChangeSetItem
SilverStripe\ORM\DataObject:
  extensions:
    - SilverStripe\Snapshots\SnapshotExtension